source 'https://rubygems.org'

# Ruby library for Appium.
gem 'appium_lib'

# Appium Ruby Console.
gem 'appium_console'

# Behaviour Driven Development with elegance and joy
gem 'cucumber'

# An IRB alternative and runtime developer console
gem 'pry-nav'

# BDD for Ruby
gem 'rspec'